services:
  backend:
    environment:
      PROMETHEUS_BASE_URL: http://mock-prometheus:9090
    depends_on:
      - mock-prometheus

  mock-prometheus:
    build:
      context: ./mock-prometheus
    ports:
      - "9090:9090"
